"""initial_schema_with_microalgos_and_listener_state

Revision ID: 95267174a74f
Revises: 
Create Date: 2026-02-18 22:05:09.442188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95267174a74f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listener_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_processed_round', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sticker_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creator_wallet', sa.String(length=58), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('ipfs_hash', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('metadata_url', sa.Text(), nullable=True),
    sa.Column('sticker_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('tip_threshold', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sticker_templates_creator_wallet'), 'sticker_templates', ['creator_wallet'], unique=False)
    op.create_table('transak_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=100), nullable=False),
    sa.Column('partner_order_id', sa.String(length=200), nullable=False),
    sa.Column('fan_wallet', sa.String(length=58), nullable=False),
    sa.Column('creator_wallet', sa.String(length=58), nullable=False),
    sa.Column('fiat_currency', sa.String(length=10), nullable=False),
    sa.Column('fiat_amount', sa.Float(), nullable=False),
    sa.Column('crypto_amount', sa.Float(), nullable=True),
    sa.Column('network_fee', sa.Float(), nullable=True),
    sa.Column('transak_fee', sa.Float(), nullable=True),
    sa.Column('platform_fee_algo', sa.Float(), nullable=True),
    sa.Column('tip_amount_algo', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('tip_tx_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('tip_sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transak_orders_creator_wallet'), 'transak_orders', ['creator_wallet'], unique=False)
    op.create_index(op.f('ix_transak_orders_fan_wallet'), 'transak_orders', ['fan_wallet'], unique=False)
    op.create_index(op.f('ix_transak_orders_order_id'), 'transak_orders', ['order_id'], unique=True)
    op.create_index(op.f('ix_transak_orders_partner_order_id'), 'transak_orders', ['partner_order_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wallet_address', sa.String(length=58), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_wallet_address'), 'users', ['wallet_address'], unique=True)
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creator_wallet', sa.String(length=58), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('app_address', sa.String(length=58), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('deployed_at', sa.DateTime(), nullable=True),
    sa.Column('upgraded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_wallet'], ['users.wallet_address'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_app_id'), 'contracts', ['app_id'], unique=True)
    op.create_index(op.f('ix_contracts_creator_wallet'), 'contracts', ['creator_wallet'], unique=False)
    op.create_table('nfts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('owner_wallet', sa.String(length=58), nullable=False),
    sa.Column('sticker_type', sa.String(length=20), nullable=False),
    sa.Column('tx_id', sa.String(length=64), nullable=True),
    sa.Column('delivery_status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('minted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['sticker_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nfts_asset_id'), 'nfts', ['asset_id'], unique=True)
    op.create_index(op.f('ix_nfts_owner_wallet'), 'nfts', ['owner_wallet'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tx_id', sa.String(length=64), nullable=False),
    sa.Column('fan_wallet', sa.String(length=58), nullable=False),
    sa.Column('creator_wallet', sa.String(length=58), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('amount_micro', sa.BigInteger(), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['contracts.app_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_creator_wallet'), 'transactions', ['creator_wallet'], unique=False)
    op.create_index(op.f('ix_transactions_fan_wallet'), 'transactions', ['fan_wallet'], unique=False)
    op.create_index(op.f('ix_transactions_tx_id'), 'transactions', ['tx_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_tx_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_fan_wallet'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_creator_wallet'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_nfts_owner_wallet'), table_name='nfts')
    op.drop_index(op.f('ix_nfts_asset_id'), table_name='nfts')
    op.drop_table('nfts')
    op.drop_index(op.f('ix_contracts_creator_wallet'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_app_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_users_wallet_address'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_transak_orders_partner_order_id'), table_name='transak_orders')
    op.drop_index(op.f('ix_transak_orders_order_id'), table_name='transak_orders')
    op.drop_index(op.f('ix_transak_orders_fan_wallet'), table_name='transak_orders')
    op.drop_index(op.f('ix_transak_orders_creator_wallet'), table_name='transak_orders')
    op.drop_table('transak_orders')
    op.drop_index(op.f('ix_sticker_templates_creator_wallet'), table_name='sticker_templates')
    op.drop_table('sticker_templates')
    op.drop_table('listener_state')
    # ### end Alembic commands ###
